/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


import {
  FitImageCompare as FitImageCompare
} from './components/fit-image-compare/fit-image-compare';

declare global {
  interface HTMLFitImageCompareElement extends FitImageCompare, HTMLStencilElement {
  }
  var HTMLFitImageCompareElement: {
    prototype: HTMLFitImageCompareElement;
    new (): HTMLFitImageCompareElement;
  };
  interface HTMLElementTagNameMap {
    "fit-image-compare": HTMLFitImageCompareElement;
  }
  interface ElementTagNameMap {
    "fit-image-compare": HTMLFitImageCompareElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fit-image-compare": JSXElements.FitImageCompareAttributes;
    }
  }
  namespace JSXElements {
    export interface FitImageCompareAttributes extends HTMLAttributes {
      modified?: string;
      original?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
