/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  NxtImageCompare as NxtImageCompare
} from './components/nxt-image-compare/nxt-image-compare';

declare global {
  interface HTMLNxtImageCompareElement extends NxtImageCompare, HTMLStencilElement {
  }
  var HTMLNxtImageCompareElement: {
    prototype: HTMLNxtImageCompareElement;
    new (): HTMLNxtImageCompareElement;
  };
  interface HTMLElementTagNameMap {
    "nxt-image-compare": HTMLNxtImageCompareElement;
  }
  interface ElementTagNameMap {
    "nxt-image-compare": HTMLNxtImageCompareElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "nxt-image-compare": JSXElements.NxtImageCompareAttributes;
    }
  }
  namespace JSXElements {
    export interface NxtImageCompareAttributes extends HTMLAttributes {
      modified?: string;
      original?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
